// LOCAL ### GET home GET http://localhost:3001

### GET all cars GET http://localhost:3001/cars

### GET specific car GET http://localhost:3001/cars/65b44999999999909db0c26eaf35826 ### Add car (POST) POST http://localhost:3001/cars Content-Type: application/json

{
  "year": "2018",
  "make": "Honda",
  "model": "CBR650R",
  "color": "Red",
  "engineSize": "649 cc",
  "transmissionType": "Manual",
  "gearCount": "6",
  "shifterType": "Foot"
}
### Update car (PUT) PUT http://localhost:3001/cars/65b4491409db0c26eaf35826 Content-Type: application/json

{
  "year": "2020",
  "make": "Honda",
  "model": "CBR650R",
  "color": "Red",
  "engineSize": "649 cc",
  "transmissionType": "Manual",
  "gearCount": "6",
  "shifterType": "Foot"
}

### Delete car DELETE http://localhost:3001/cars/65b5531192d8bd32775c664f

// PRODUCTION ### GET home GET https://cse341bh-project2.onrender.com

### GET all cars GET https://cse341bh-project2.onrender.com/cars

### GET specific car GET https://cse341bh-project2.onrender.com/cars/65b447ec09db0c26eaf35824

### Add car (POST car) POST https://cse341bh-project2.onrender.com/cars Content-Type: application/json

{
  "year": "2020",
  "make": "Yamaha",
  "model": "YZF-R1",
  "color": "Black",
  "engineSize": "998 cc",
  "transmissionType": "Manual",
  "gearCount": "6",
  "shifterType": "Foot"
}

### Change car information (PUT) PUT https://cse341bh-project2.onrender.com/cars/65b447ec09db0c26eaf35824 Content-Type: application/json

{
  "year": "2022",
  "make": "Harley-Davidson",
  "model": "Fat Boy",
  "color": "Blue",
  "engineSize": "1868 cc",
  "transmissionType": "Manual",
  "gearCount": "6",
  "shifterType": "Foot"
}
### Remove a car (DELETE) DELETE https://cse341bh-project2.onrender.com/cars/65b5552136a57602a84003